### ISSUE TITLE
How do I run this locally? (I got  Flutter installed (flutter doctor safe) but I cant run.

### ISSUE THREAD

**Issue by kogake** [Ochibobo/odoo_dart#2]
(Imagine that im a legit no code guy)

**Comment by Ochibobo** [comment]
Hey..
What are you trying to achieve?

**Comment by kogake** [comment]
Now I got it ahahahha, my bad.

I looked for what is odoo and got it.

I am just looking for help with creating an erp (inventory control) flutter app for my College classes.

**Comment by Ochibobo** [comment]
It's OK..

That's seems like an interesting project to undertake. Are you looking into
writing the entire app in Flutter?

What about the backend stack (are you familiar with this term) ??

**Comment by kogake** [comment]
So its just like an mvp but Im trying to make it bigger.

At front end I was thinking about getting some ideas with flutter as we will try to expand for web apps after.

I just worked with back end in a bank, but it was in C#. I have no clue about the back end... Do you know something here I dont know even how to start :/

Thinking about the database, I will get google firebase.

**Comment by Ochibobo** [comment]
Nice idea.

Congrats on working on the backend of a bank in C#.

Don't worry, you'll soon get to understand stuff the more you
practise/learn. Given that you are using firebase for this project, then
you don't necessarily have to create a separate backend stack for your
project. What you can do is check out some tutorials on Firebase and how to
integrate a Flutter app with firebase. There are a lot of materials
available. Furthermore, there are flutter libraries that will help you out
when integrating.

**Comment by kogake** [comment]
I appreciate your comments. Im really new to full stack and I didnt knew that I didnt know to create a separete backend stack, I was lagging a lot at this part of the architecture. I will try it! 

Thank you very much :)
